pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=gvolpe
      - title~=(?i)Update
      - body~=(?i)Configure Scala Steward for your repository
    actions:
      label:
        add: [dependency-update]
  - name: automatically merge gvolpe's Scala Steward PRs on CI success
    conditions:
      - author=gvolpe
      - title~=(?i)Update
      - body~=(?i)Configure Scala Steward for your repository
      - status-success=Build
    actions:
      merge:
        method: merge
