name: Scala

on:
  pull_request: {}
  push:
    branches:
      - series/1.x # CE3
      - series/2.x
    paths:
      - "modules/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: "Starting up Redis 🐳"
        run: docker compose up -d

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v6

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31.2.0

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v16
        with:
          name: profunktor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Run tests and compile documentation 🚀"
        run: nix run .#sbt -- buildRedis4Cats

      - name: Check for untracked changes
        run: |
          git status
          ./scripts/check_dirty.sh

      - name: "Test for Binary Compatibility 📦"
        run: nix run .#sbt mimaReportBinaryIssuesIfRelevant

      - name: "Shutting down Redis 🐳"
        run: docker compose down
